### ISSUE TITLE
union: column named 'TableName' already exists - Workspace Usage Report

### ISSUE THREAD

**Issue by VishCQG** [clivewatson/KQLpublic#1]
The workbook use to work but now comes up with this error:

union: column named 'TableName' already exists
Click to Retry.

Some parts of the workbook are still populating with data but 90% of the work book is broken. Same issue on both the Workspace Usage Report v1.3 and Workspace Usage Report v1.4
![workbook error](https://user-images.githubusercontent.com/47391110/85718935-e5103780-b6e6-11ea-8094-483776494193.jpg)

**Comment by CliveW-MSFT** [comment]
Hi, Apologies,  I missed this!  There is a clash with the SQL solution: "  SQL Data Discovery & Classification”.  I'll change the name in the next release to fix this.  As a workaround, edit the JSON to find & replace of 'withsource=TableName' to 'withsource=TableName1'  (or any new name that is unique)
